# Generated by Django 5.0.1 on 2024-01-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
