# Generated by Django 5.0.1 on 2024-01-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('inv_num', models.IntegerField()),
                ('commissioning', models.DateField()),
                ('depreciation', models.DateField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemtype', to_field='type_name')),
            ],
        ),
    ]
