# Generated by Django 5.0.1 on 2024-01-23 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='placement',
            field=models.CharField(default=True, max_length=40),
        ),
        migrations.AddField(
            model_name='item',
            name='system',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.DeleteModel(
            name='ItemType',
        ),
    ]
