# Generated by Django 5.0.1 on 2024-01-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='item',
        ),
    ]
