# Generated by Django 5.0.1 on 2024-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_post_comment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='system',
        ),
        migrations.AddField(
            model_name='item',
            name='system',
            field=models.ManyToManyField(related_name='items', to='inventory.system'),
        ),
    ]
