# Generated by Django 5.0.1 on 2024-01-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_item_system_delete_system_item_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='system',
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=40, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='systems',
            field=models.ManyToManyField(related_name='items', to='inventory.system'),
        ),
    ]
