# Generated by Django 5.0.1 on 2024-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
    ]
